cookie_key: ''
save_path: ''
headless: True
url: ''
binary_location: 'driver/chromedriver'
user_agent:
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
